name: chill-out

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  chill-builder:
    runs-on: macos-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p data-raw && curl -s https://www.thebiggchill.com/flavors -o "data-raw/$(date +%Y-%m-%dT%H:%M:%S%z).html"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: more chill
          commit_author: Author <actions@github.com>
  site-builder:
    needs: ${{ github.event_name != 'workflow_dispatch' && 'chill-builder' || null }}
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Fetch remote changes
        run: git fetch origin main
      - name: Merge remote changes
        run: git merge origin/main --no-edit
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "rvest", "here", "fs", "DT"), dependencies = TRUE)'
      - name: Render Rmd
        run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chill website updated
          commit_author: Author <actions@github.com>
